config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  get 'profile' => 'pages#profile', as: :profile
  get 'contact' => 'pages#contact', as: :contact

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	@time_now = Time.now
  end

  def profile
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | Training</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'shared/navbar' %>
<div class="main-page-content <%= controller.controller_name %>">
	<%= yield %>
</div>

</body>
</html>

app/views/pages/contact.html.erb
<%= provide(:contact,"active") %>
<%= provide(:title,"Contact") %>

    <section class="container">
        <div class="row">
            <div class="col-md-3">
                <h2>Riku Kiranatama</h2>
                <img src="http://www.8opon.pl/images/business_user_big.png" class="img-thumbnail img-circle profile">
            </div>
            <div class="col-sm-9 col-md-9">
                <form class="form-horizontal" role="form">
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="email">Email</label>
                        <div class="col-sm-8 pull-right">
                            <input type="email" class="form-control" placeholder="Email Anda">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="message">Messages</label>
                        <div class="col-sm-8 pull-right"> 
                            <textarea class="form-control" rows="7" placeholder="Messages Anda"></textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-3">
                            <button type="submit" class="btn btn-default">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>

app/views/pages/index.html.erb
<%= provide(:index,"active") %>
<%= provide(:title,"Home") %>

	<section class="container">
		<div id="myCarousel" class="carousel slide">
      		<ol class="carousel-indicators">
        		<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        		<li data-target="#myCarousel" data-slide-to="1"></li>
      		</ol>
      		<div class="carousel-inner">
        		<div class="item active">
          			<img src="http://thewallpaperhost.com/wp-content/uploads/2015/09/nature-wallpaper-362.jpeg" alt="1slide" id="img-control">
          			<div class="container">
            			<div class="carousel-caption">
              				<h1>Gang Di Kota Bandung</h1>
            			</div>
          			</div>
        		</div>
        		<div class="item">
          			<img src="http://fionaparr-focusing.co.uk/wp-content/uploads/2014/10/trees-nature.jpg" id="img-control" alt="2slide">
          			<div class="container">
            			<div class="carousel-caption">
              				<h1>Keindahan Kota Bandung</h1>
            			</div>
          			</div>
        		</div>
      		</div>
      
      		<a class="left carousel-control" href="#myCarousel" data-slide="prev">
      			<span class="glyphicon glyphicon-chevron-left"></span>
      		</a>
      		<a class="right carousel-control" href="#myCarousel" data-slide="next">
      			<span class="glyphicon glyphicon-chevron-right"></span>
      		</a>
    	</div>
	</section>
	
	<section class="container">
		<div class="row">
			<div class="col-sm-4 col-md-4">
				<p>Hallo Saya Riku dan saya saat ini akan lulus kuliah, salam kenal yah. Berikut contoh dari design grafik yang saya buat :)</p>
			</div>
			<div class="pull-right col-sm-4 col-md-4">
				Facebook : riku@mail.com<br/>
				Twitter : riku@mail.com<br/>
				Telepon : 022-232392<br/>
				Alamat : Jl.Harapan Bangas No.23,Bandung,Indonesia
			</div>
		</div>
	</section>

  <footer class="container">
    <p>Today : <%= @time_now %></p>
  </footer>

app/views/pages/profile.html.erb
<%= provide(:profile,"active")
provide(:title,"Profile") %>

    <section class="container">
        <div class="row">
            <div class="col-md-3">
                <h2>Riku Kiranatama</h2>
                <img src="http://www.8opon.pl/images/business_user_big.png" class="img-thumbnail img-circle profile">
            </div>
            <div class="col-sm-9 col-md-9">
                <div class="table-responsive">
                    <table class="table table-hover table-striped">
                        <tbody>
                            <tr>
                                <td><b>Nama</b></td>
                                <td>Riku Kiranatama</td>
                            </tr>
                            <tr>
                                <td><b>Tempat,Tanggal Lahir</b></td>
                                <td>Bandung,7 Oktober 1989</td>
                            </tr>
                            <tr>
                                <td><b>Jenis Kelamin</b></td>
                                <td>Pria</td>
                            </tr>
                            <tr>
                                <td><b>Alamat Domisili</b></td>
                                <td>Jl.Soekarno-Hatta No.104</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>

app/views/shared/_navbar.html.erb
<header>
    <div id="navbar" class="navbar navbar-default">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Training Bootstrap</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="pull-right nav navbar-nav">
            	<li class="<%= yield(:index) %>"><%= link_to "Home", root_path %></li>
                <li class="<%= yield(:profile) %>"><%= link_to "Profile", profile_path %></li>
                <li class="<%= yield(:contact) %>"><%= link_to "Contact", contact_path %></li>
            </ul>
        </div>
    </div>
</header>